# Generated by Django 4.2.3 on 2023-07-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_one', models.CharField(max_length=50)),
                ('field_two', models.CharField(max_length=50)),
            ],
        ),
    ]
