# Generated by Django 4.2.3 on 2023-07-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.CharField(max_length=500)),
                ('category_img1', models.CharField(max_length=200)),
                ('category_img2', models.CharField(max_length=200)),
                ('category_img3', models.CharField(max_length=200)),
                ('active_offer_total', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
