# Generated by Django 4.2.3 on 2023-07-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_feedback_delete_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='active_offer_total',
            new_name='active_listing_total',
        ),
    ]
