# Generated by Django 4.2.3 on 2023-07-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_active_offer_total_category_active_listing_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(max_length=200)),
                ('listing_description', models.CharField(max_length=500)),
                ('listing_comp_type', models.CharField(choices=[('For A Skill', 'For A Skill'), ('For A Fee', 'For A Fee'), ('For Free', 'For Free')], max_length=20)),
                ('listing_status', models.CharField(choices=[('Active', 'Active'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn'), ('Inactive', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='main_app.category')),
            ],
        ),
    ]
