# Generated by Django 4.2.3 on 2023-07-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('Skill', 'Skill'), ('Need', 'Need')], default='Skill Swap/Trade', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_comp_type',
            field=models.CharField(choices=[('Skill Swap/Trade', 'Skill Swap/Trade'), ('Paid/Fee-based', 'Paid/Fee-based'), ('Free/No charge', 'Free/No charge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_description',
            field=models.TextField(max_length=500),
        ),
    ]
