# Generated by Django 4.2.3 on 2023-07-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_listing_listing_type_alter_listing_listing_comp_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_img1',
            field=models.CharField(default='https://i.imgur.com/tvBdJVL.png', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_img2',
            field=models.CharField(default='https://i.imgur.com/tvBdJVL.png', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_img3',
            field=models.CharField(default='https://i.imgur.com/tvBdJVL.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_img1',
            field=models.CharField(default='https://i.imgur.com/hGiBFyv.png', max_length=200),
        ),
    ]
