# Generated by Django 4.2.3 on 2023-07-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_listing_listing_img1_listing_listing_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_comp_type',
            field=models.CharField(choices=[('Skill Swap/Trade', 'Skill Swap/Trade'), ('Paid/Fee-based', 'Paid/Fee-based'), ('Free/No charge', 'Free/No charge'), ("I'm Flexible!", "I'm Flexible!")], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
