# Generated by Django 4.2.3 on 2023-07-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_comp_type',
            field=models.CharField(blank=True, choices=[('Skill Swap/Trade', 'Skill Swap/Trade'), ('Paid/Fee-based', 'Paid/Fee-based'), ('Free/No charge', 'Free/No charge'), ("I'm Flexible!", "I'm Flexible!")], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_img1',
            field=models.CharField(blank=True, default='https://i.imgur.com/tvBdJVL.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_img2',
            field=models.CharField(blank=True, default='https://i.imgur.com/tvBdJVL.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_img3',
            field=models.CharField(blank=True, default='https://i.imgur.com/tvBdJVL.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('Skill', 'Skill'), ('Need', 'Need')], default='Skill Swap/Trade', max_length=10),
        ),
    ]
