# Generated by Django 4.2.3 on 2023-07-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_category',
            field=models.BooleanField(default=False),
        ),
    ]
