INSERT INTO main_app_category(category_name, category_description, category_img1, category_img2, category_img3, active_listing_total, created_at, featured_category)
    VALUES
    ('Cooking', 'Cooking, cookery, or culinary arts is the art, science and craft of using heat to make food more palatable, digestible, nutritious, or safe. Cooking techniques and ingredients vary widely, from grilling food over an open fire to using electric stoves, to baking in various types of ovens, reflecting local conditions. Types of cooking also depend on the skill levels and training of the cooks. Cooking is done both by people in their own dwellings and by professional cooks and chefs in restaurants and other food establishments.', 'https://i0.wp.com/blog.frontiersin.org/wp-content/uploads/2017/07/frontiers-in-ict-food-bridging.jpg?resize=940%2C625&ssl=1', 'https://t4.ftcdn.net/jpg/02/54/93/61/360_F_254936166_5MFxlGv7PNPw4VmpuNNQxlU0K2D4f7Ya.jpg', 'https://previews.123rf.com/images/subbotina/subbotina1110/subbotina111000047/10996532-kitchen-cooking-closeup.jpg', 0, '2023-03-01 00:00:00-06', true);

INSERT INTO main_app_category(category_name, category_description, category_img1, category_img2, category_img3, active_listing_total, created_at, featured_category)
    VALUES
    ('Outdoor/Sports', 'Sport pertains to any form of physical activity or game,[1] often competitive and organized, that aims to use, maintain, or improve physical ability and skills while providing enjoyment to participants and, in some cases, entertainment to spectators.[2] Sports can, through casual or organized participation, improve participants'' physical health. Hundreds of sports exist, from those between single contestants, through to those with hundreds of simultaneous participants, either in teams or competing as individuals. In certain sports such as racing, many contestants may compete, simultaneously or consecutively, with one winner; in others, the contest (a match) is between two sides, each attempting to exceed the other. ', 'https://img.freepik.com/free-photo/sports-tools_53876-138077.jpg?w=2000', 'https://media.istockphoto.com/id/1355687112/photo/various-sport-equipment-gear.webp?b=1&s=170667a&w=0&k=20&c=hEADFXL4HG9mF94yC5g3JA8lMHn8OZg7hRLoiel_L48=', 'https://res.cloudinary.com/jnto/image/upload/w_650,h_432,f_auto,fl_lossy,q_auto,c_fill/v1/media/filer_public/e9/f4/e9f4b61e-fd8d-4761-b6ae-eed35f02c7c4/kv_hiking_bghcg9', 0, '2023-03-02 00:00:00-06', true);

INSERT INTO main_app_category(category_name, category_description, category_img1, category_img2, category_img3, active_listing_total, created_at, featured_category)
    VALUES
    ('Languages', 'Language is a structured system of communication that consists of grammar and vocabulary. It is the primary means by which humans convey meaning, both in spoken and written forms, and may also be conveyed through sign languages. The vast majority of human languages have developed writing systems that allow for the recording and preservation of the sounds or signs of language. Human language is characterized by its cultural and historical diversity, with significant variations observed between cultures and across time.[1] Human languages possess the properties of productivity and displacement, which enable the creation of an infinite number of sentences, and the ability to refer to objects, events, and ideas that are not immediately present in the discourse. The use of human language relies on social convention and is acquired through learning.', 'https://www.timeshighereducation.com/student/sites/default/files/styles/default/public/languages-signpost.jpg?itok=krMV75kb', 'https://sp-ao.shortpixel.ai/client/to_auto,q_lossy,ret_img,w_1024,h_724/https://localizationlab.com/wp-content/uploads/2021/05/IMAGE_TRANSLATION-8-1024x724.png', 'https://www.fluentu.com/blog/educator/wp-content/uploads/sites/9/2017/03/how-to-be-a-good-language-teacher-e1490591348601.jpg', 0, '2023-03-03 00:00:00-06', false);

INSERT INTO main_app_category(category_name, category_description, category_img1, category_img2, category_img3, active_listing_total, created_at, featured_category)
    VALUES
    ('Consulting', 'A consultant (from Latin: consultare "to deliberate") is a professional (also known as expert, specialist, see variations of meaning below) who provides advice or services in an area of specialization (generally to medium or large-size corporations). Consulting services generally fall under the domain of professional services, as contingent work. The Harvard Business School defines a consultant as someone who advises on "how to modify, proceed in, or streamline a given process within a specialized field". According to Institute of Management Consultants USA, "The value of a consultant [as compared to a subject-matter expert (SME)] is to be able to correctly diagnose and effectively transform an often ill-defined problem and apply information, resources and processes to create a workable and usable solution.', 'https://www.opentext.com/assets/images/services-support/opentext-image-ov-service-portfolio-consulting-services-en.jpg', 'https://fjwp.s3.amazonaws.com/blog/wp-content/uploads/2021/06/24144753/consulting-jobs-1024x512-b-1-1.jpeg', 'https://thumbs.dreamstime.com/b/business-consulting-concept-virtual-screen-business-consulting-concept-virtual-screen-153994074.jpg', 0, '2023-03-04 00:00:00-06', false);

INSERT INTO main_app_category(category_name, category_description, category_img1, category_img2, category_img3, active_listing_total, created_at, featured_category)
    VALUES
    ('Art/Creativity', 'Creativity is a phenomenon whereby something new and valuable is formed. The created item may be intangible (such as an idea, a scientific theory, a musical composition, or a joke) or a physical object (such as an invention, a printed literary work, or a painting). Scholarly interest in creativity is found in a number of disciplines, primarily psychology, business studies, and cognitive science. However, it can also be found in education, the humanities (philosophy, the arts) and theology, social sciences (sociology, linguistics, economics), engineering, technology and mathematics. These disciplines cover the relations between creativity and general intelligence, personality type, mental and neural processes, mental health, artificial intelligence; the potential for fostering creativity through education, training, leadership and organizational practices;[1][2] the factors that determine how creativity is evaluated and perceived;[3] the fostering of creativity for national economic benefit; and the application of creative resources to improve the effectiveness of teaching and learning.', 'https://images.hindustantimes.com/rf/image_size_960x540/HT/p2/2020/06/28/Pictures/_5a4397c2-b944-11ea-9350-67a6fbf842e0.jpg', 'https://creativeartworksblog.files.wordpress.com/2020/07/creativity-tekisband.jpg', 'https://img.freepik.com/premium-photo/creative-mind-concept-intelligence-art-collage-white-background-generative-ai_58409-30549.jpg?w=2000', 0, '2023-03-05 00:00:00-06', false);

INSERT INTO main_app_category(category_name, category_description, category_img1, category_img2, category_img3, active_listing_total, created_at, featured_category)
    VALUES
    ('Do It Yourself', '"Do it yourself" ("DIY") is the method of building, modifying, or repairing things by oneself without the direct aid of professionals or certified experts. Academic research has described DIY as behaviors where "individuals use raw and semi-raw materials and parts to produce, transform, or reconstruct material possessions, including those drawn from the natural environment (e.g., landscaping)". DIY behavior can be triggered by various motivations previously categorized as marketplace motivations (economic benefits, lack of product availability, lack of product quality, need for customization), and identity enhancement (craftsmanship, empowerment, community seeking, uniqueness).', 'https://massolutions.biz/wp-content/uploads/2014/10/bigstock-Do-it-Yourself-concept-28287233.jpg', 'https://www.bbva.com/wp-content/uploads/2022/02/BBVA-Do-it-yourself.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsq8WNxCX_mwjplCQl1xSDjujLRnpUg7wJ8EEu5thBQA5mJ-tuU5yqquN9_w1KDsoRTWw&usqp=CAU', 0, '2023-03-06 00:00:00-06', false);

INSERT INTO main_app_category(category_name, category_description, category_img1, category_img2, category_img3, active_listing_total, created_at, featured_category)
    VALUES
    ('Music', 'Music is generally defined as the art of arranging sound to create some combination of form, harmony, melody, rhythm, or otherwise expressive content.[1][2][3] Definitions of music vary depending on culture,[4] though it is an aspect of all human societies and a cultural universal.[5] While scholars agree that music is defined by a few specific elements, there is no consensus on their precise definitions.[6] The creation of music is commonly divided into musical composition, musical improvisation, and musical performance,[7] though the topic itself extends into academic disciplines, criticism, philosophy, and psychology. Music may be performed or improvised using a vast range of instruments, including the human voice.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScevBMOrU2JEK3H7JKo8qEG_MjfAgc6ITlpg&usqp=CAU', 'https://rare-gallery.com/uploads/posts/533426-music-ghost.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-Apu1JPEhQk5HgxHA4jqlmFMVPVfl6ji1RQ&usqp=CAU', 0, '2023-03-07 00:00:00-06', false);

INSERT INTO main_app_category(category_name, category_description, category_img1, category_img2, category_img3, active_listing_total, created_at, featured_category)
    VALUES
    ('Beauty/Health', 'In common usage and medicine, health, according to the World Health Organization, is "a state of complete physical, mental and social well-being and not merely the absence of disease and infirmity". A variety of definitions have been used for different purposes over time. Health can be promoted by encouraging healthful activities, such as regular physical exercise and adequate sleep, and by reducing or avoiding unhealthful activities or situations, such as smoking or excessive stress. Some factors affecting health are due to individual choices, such as whether to engage in a high-risk behavior, while others are due to structural causes, such as whether the society is arranged in a way that makes it easier or harder for people to get necessary healthcare services. Still, other factors are beyond both individual and group choices, such as genetic disorders.', 'https://media.istockphoto.com/id/1141698953/photo/spa-products-for-home-skin-care.webp?b=1&s=170667a&w=0&k=20&c=JzqLCaVnKh237TY-4ldl8yfPNPh-u13oCBlPPGYcFDA=', 'https://healthandbeautyclinic.london/wp-content/uploads/2023/07/hot-stone-massage38602527_xl-770x410.jpg', 'https://cloudfront-eu-central-1.images.arcpublishing.com/businessoffashion/LT3UDJQBSJCBTJURUJBGJIWKBU.jpg', 0, '2023-03-08 00:00:00-06', true);

INSERT INTO main_app_category(category_name, category_description, category_img1, category_img2, category_img3, active_listing_total, created_at, featured_category)
    VALUES
    ('Care/Sitting', 'A caregiver, carer or support worker is a paid or unpaid member of a person''s social network who helps them with activities of daily living. Since they have no specific professional training, they are often described as informal caregivers. Caregivers most commonly assist with impairments related to old age, disability, a disease, or a mental disorder. Typical duties of a caregiver might include taking care of someone who has a chronic illness or disease; managing medications or talking to doctors and nurses on someone''s behalf; helping to bathe or dress someone who is frail or disabled; or taking care of household chores, meals, or processes both formal and informal documentation related to health for someone who cannot do these things alone.', 'https://elderaffairs.org/wp-content/uploads/caregiver-supoort-scaled.jpeg', 'https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/11/834360-Best-Babysitting-websites-and-Apps-1296x728-Header-01adb9.jpg?w=1155&h=1528', 'https://cdn.petcloud.com.au/d/wp-content/uploads/2022/03/04172134/dos-and-donts-of-pet-sitting.png', 0, '2023-03-09 00:00:00-06', true);

INSERT INTO main_app_category(category_name, category_description, category_img1, category_img2, category_img3, active_listing_total, created_at, featured_category)
    VALUES
    ('Computer/IT', 'Information technology (IT) is the use of computers to create, process, store, retrieve and exchange all kinds of data[1] and information. IT forms part of information and communications technology (ICT).[2] An information technology system (IT system) is generally an information system, a communications system, or, more specifically speaking, a computer system — including all hardware, software, and peripheral equipment — operated by a limited group of IT users, and an IT project usually refers to the commissioning and implementation of an IT system.', 'https://gradlime.com/wp-content/uploads/2017/10/IT-computer-science-computer-engineering-degrees.png', 'https://www.computersciencedegreehub.com/wp-content/uploads/2022/07/computer-engineering.jpg', 'https://www.tutorialspoint.com/basics_of_computer_science/images/programmer.jpg', 0, '2023-03-10 00:00:00-06', false);

INSERT INTO main_app_category(category_name, category_description, category_img1, category_img2, category_img3, active_listing_total, created_at, featured_category)
    VALUES
    ('Education', 'Education is the transmission of knowledge, skills, and character traits. There are many debates about its precise definition, for example, about which aims it tries to achieve. A further issue is whether part of the meaning of education is that the change in the student is an improvement. Some researchers stress the role of critical thinking to distinguish education from indoctrination. These disagreements affect how to identify, measure, and improve forms of education. The term can also refer to the mental states and qualities of educated people. Additionally, it can mean the academic field studying education.', 'https://habitatbroward.org/wp-content/uploads/2020/01/10-Benefits-Showing-Why-Education-Is-Important-to-Our-Society.jpg', 'https://static-cse.canva.com/blob/567850/educationisimportant.jpg', 'https://homeguruworld.com/wp-content/uploads/2021/05/Banner-1-e1632383732604.jpg', 0, '2023-03-11 00:00:00-06', true);

INSERT INTO main_app_category(category_name, category_description, category_img1, category_img2, category_img3, active_listing_total, created_at, featured_category)
    VALUES
    ('Others', 'Any and all skills or services that don''t align with the primary categories.', 'https://www.salesforce.com/content/dam/web/en_us/www/images/hub/how-to-close-the-sale/list-of-most-important-customer-service-skills-header.jpg', 'https://i.guim.co.uk/img/media/ef96c1f2495b60ec83379962d4aec38bfb1ce039/0_187_5600_3363/master/5600.jpg?width=1200&quality=85&auto=format&fit=max&s=f0198ef0d8b34258c6b8b494ca82669e', 'https://www.artnews.com/wp-content/uploads/2020/06/shutterstock_147651662.jpg', 0, '2023-03-12 00:00:00-06', false);