INSERT INTO main_app_listing(listing_name, listing_description, listing_img1, listing_img2, listing_img3, listing_type, listing_comp_type, listing_status, created_at, category_id)
    VALUES
    ('French cooking at home', 'I will come to your place for a 1 hour French cooking class with a seasonal 2 course menu. All you will need to provide is a clean cooktop and oven in good working condition. Valid in New Haven greater area. Surcharge applies to other locations in CT. Can also be swapped with other services equivalent in Skillharbour time and/or value.', 'https://thefoxmagazine.com/wp-content/uploads/2023/05/pexels-cottonbro-studio-4686829-scaled.jpg', 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGNvb2tpbmd8ZW58MHx8MHx8fDA%3D&w=1000&q=80', 'https://www.wellandgood.com/wp-content/uploads/2019/12/Stocksy-cooking-for-one-Andrey-Pavlov-425x285.jpeg', 'Skill', 'Paid/Fee-based', 'Active', '2023-07-18 00:00:00-06', 20);

INSERT INTO main_app_listing(listing_name, listing_description, listing_img1, listing_img2, listing_img3, listing_type, listing_comp_type, listing_status, created_at, category_id)
    VALUES
    ('Versatile kitchen guru offers services', 'You know how to hold a cooking spoon, but not how to use it? Then we should meet. Something light, Thai or Italian Bolognese, or would you prefer original Spaghetti Carbonara? Hungarian goulash or Spanish gazpacho? Or schnitzel, dumplings, roast or a Swiss dish? Or would you like to learn to bake? Then let''s go!', 'http://www.skillharbour.com/media/tmp/skill/eaf42201-3061-486d-b681-49b10354838c.jpg.620x370_q85_crop_upscale.jpg', 'https://img.freepik.com/free-photo/close-up-cook-preparing-dessert_23-2148972039.jpg', 'https://www.yourfreecareertest.com/wp-content/uploads/2016/07/pastry_chef_baker.jpg', 'Skill', 'Paid/Fee-based', 'Active', '2023-07-18 00:00:00-06', 20);

INSERT INTO main_app_listing(listing_name, listing_description, listing_img1, listing_img2, listing_img3, listing_type, listing_comp_type, listing_status, created_at, category_id)
    VALUES
    ('Food Nutrition & Cooking Support', 'I''ve read countless book on nutrition. I myself am in very good shape as for the past 7 years. we can talk grocery shopping, home cooking, bigger concept, whatever you''d like.', 'http://www.skillharbour.com/media/tmp/skill/69b505b3-57d7-4356-a34c-dc197b89974e.webp.620x370_q85_crop_upscale.jpg', 'https://images.pexels.com/photos/2284166/pexels-photo-2284166.jpeg?cs=srgb&dl=pexels-maarten-van-den-heuvel-2284166.jpg&fm=jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrMpPxmM4WW4biQO9kn3QuBVVnRU17U_zfItNWqdTTEXAWtIb53ulOe5zRMSvYR8xSIYo&usqp=CAU', 'Skill', 'Skill Swap/Trade', 'Active', '2023-07-10 00:00:00-06', 20);

-- Cooking end

INSERT INTO main_app_listing(listing_name, listing_description, listing_img1, listing_img2, listing_img3, listing_type, listing_comp_type, listing_status, created_at, category_id)
    VALUES
    ('Go/Weiqi/Baduk lessons in exchange for Polish/Esperanto', 'I am a beginning go player (about 11-9 kyu on OGS) and would be very happy to receive teaching games/lessons from SDK or dan players. Online or in Kraków. In exchcange I can offer Polish or Esperanto lessons (see my skill offers).', 'http://www.skillharbour.com/media/tmp/skill/d6f24a55-3800-44da-b2c0-580ebd6f3571.jpg.620x370_q85_crop_upscale.jpg', 'https://www.ft.com/__origami/service/image/v2/images/raw/http%3A%2F%2Fcom.ft.imagepublish.upp-prod-eu.s3.amazonaws.com%2F9df76efc-e6b3-11e5-a09b-1f8b0d268c39?dpr=1&fit=scale-down&source=next&width=540', 'https://i.redd.it/ckg2flcdd9s41.png', 'Need', 'Skill Swap/Trade', 'Active', '2023-07-05 00:00:00-06', 21);

INSERT INTO main_app_listing(listing_name, listing_description, listing_img1, listing_img2, listing_img3, listing_type, listing_comp_type, listing_status, created_at, category_id)
    VALUES
    ('Rock Climbing Instructor', 'I am a certified Mountaineering and Rock Climbing Instructor, currently working in North Wales and Spain. I can teach and guide people on rock climbs and mountains in North Wales and Spain', 'https://visitidaho.org/content/uploads/2021/11/CityOfRocks_CodyLee_BuildingBlocks_TheMechanic12plus-scaled.jpg', 'https://www.miyaradventures.com/wp-content/uploads/2015/07/Feature_Image_GirlClimbing.jpg', 'https://img.grouponcdn.com/pwa_test/jGaD369Duz8yh2eS8VDHCZA8XXk/jG-720x480/v1/t600x362.jpg', 'Skill', 'I''m Flexible!', 'Active', '2023-07-06 00:00:00-06', 21);

INSERT INTO main_app_listing(listing_name, listing_description, listing_img1, listing_img2, listing_img3, listing_type, listing_comp_type, listing_status, created_at, category_id)
    VALUES
    ('Teaching Handstand, Headstand, Cartwheel', 'I have been practicing gymnastics for 10 years and Acroyoga for about 5 years. I love doing Handstand: standing still, different ways of getting up, turning, walking around and I am currently training to do a handstand on one hand. I can help you to get more confidence and show you some tricks.', 'http://www.skillharbour.com/media/tmp/skill/b67d2da9-1944-4701-86c6-1cc09f18513f.jpeg.620x370_q85_crop_upscale.jpg', 'https://www.blueosa.com/wp-content/uploads/2018/11/How-To-Do-Headstand.jpg', 'https://wellnessworks.in/wp-content/uploads/2019/06/headstand-1.jpg', 'Skill', 'Free/No Charge', 'Active', '2023-07-06 00:00:00-06', 21);

INSERT INTO main_app_listing(listing_name, listing_description, listing_img1, listing_img2, listing_img3, listing_type, listing_comp_type, listing_status, created_at, category_id)
    VALUES
    ('Seeking a surfer buddy/mentor', 'I''ve had a couple of sporadic surf lessons, but am looking for an experienced surfer to tag along with, mainly to be able to go at the right place/time, learn to read waves and get moral support. I have all the gear, just need someone to meet up with! In exchange, I have an extensive accounting background, marketing skills, as well as physical therapy (anatomy) knowledge.', 'https://images.pexels.com/photos/390051/surfer-wave-sunset-the-indian-ocean-390051.jpeg?cs=srgb&dl=pexels-pixabay-390051.jpg&fm=jpg', 'https://www.santamonica.com/wp-content/uploads/2022/06/santa-monica-surfing.jpg', 'https://www.rapturecamps.com/wp-content/uploads/2021/06/Rapturecamps-2017-03-20-1243.jpg', 'Need', 'I''m Flexible', 'Active', '2023-06-06 00:00:00-06', 21);

-- Outdoor/Sports end

INSERT INTO main_app_listing(listing_name, listing_description, listing_img1, listing_img2, listing_img3, listing_type, listing_comp_type, listing_status, created_at, category_id)
    VALUES
    ('Let''s have a chess lesson in English!', 'Hi! I''m an experienced chess coach, I give chess classes for people. My goal is to be more fluent in English. I know some vocabulary, grammar and I can write simple phrases like this. I''d like to also fix my talking which I didn''t improve for a long time.', 'http://www.skillharbour.com/media/tmp/skill/fb8d76c7-f1aa-49c7-8d72-8457a1bf432e.png.620x370_q85_crop_upscale.png', 'https://www.incimages.com/uploaded_files/image/1920x1080/getty_BA65213_9707769704500326_49933.jpg', 'https://image1.masterfile.com/getImage/NjE0LTA3MjM0OTAxZW4uMDAwMDAwMDA=AEbI$X/614-07234901en_Masterfile.jpg', 'Need', 'Free/No Charge', 'Active', '2023-06-08 00:00:00-06', 22);

INSERT INTO main_app_listing(listing_name, listing_description, listing_img1, listing_img2, listing_img3, listing_type, listing_comp_type, listing_status, created_at, category_id)
    VALUES
    ('Need English in exchange for Javascript and React teaching', 'Hello! My name is John and I''m a Software Engineer with 3 years experience. I want to improve my English skills. Feel free to message me if you want to improve your programming skills (Javascript, React, Git, etc.)!', 'https://alis.alberta.ca/media/697690/software-engineer-shutterstock-401334661.jpg', 'https://woz-u.com/wp-content/uploads/2020/02/What-Do-Software-Engineers-Do-WOZ-2-min.png', 'https://cms-assets.themuse.com/media/lead/_1200x630_crop_center-center_82_none/4decc451-b321-49da-a776-0ab7c8c072f7.png?mtime=1572888483', 'Need', 'Skill Swap/Trade', 'Active', '2023-07-10 00:00:00-06', 22);

INSERT INTO main_app_listing(listing_name, listing_description, listing_img1, listing_img2, listing_img3, listing_type, listing_comp_type, listing_status, created_at, category_id)
    VALUES
    ('Chinese Lanuage Lessons', 'Help for those who want to learn Chinese! Chinese is my mother tongue. From basic pronunciation to advanced idioms can be taught. If you are interested in Chinese, welcome to ask me.', 'https://media.istockphoto.com/id/997790960/photo/learning-chinese-alphabet-pinyin-in-class-room.jpg?s=612x612&w=0&k=20&c=uhTmLjBaxtvDv6zVHpvjOdiK8nU1RZ5Q4hSSFT0AKBI=', 'https://media.istockphoto.com/id/460766243/photo/rear-view-of-students-learning-chinese-writing-on-chalkboard.jpg?s=612x612&w=0&k=20&c=1mI4MH3lzCpRnu_NX1Lqb8Qa7dwBhIPWjMRWwauP5k8=', 'https://uploads-ssl.webflow.com/5de551efc96eff9aad542bdb/5e1cc9b7a181690fa4a6ad7f_Chalkboard-Chinese-w1000.jpg', 'Skill', 'Paid/Fee-based', 'Active', '2023-07-10 00:00:00-06', 22);